// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failure`

/// Bakes the image's EXIF orientation into its pixel data and re-encodes as
/// JPEG, so every consumer (Rust solving, Flutter display, history
/// thumbnails) shares one unambiguous pixel layout.
///
/// This matters because `image::load_from_memory` does **not** auto-rotate
/// on decode (confirmed against `image` 0.25.10's source — `Orientation` must
/// be read from the decoder and applied explicitly), and Flutter's own image
/// widgets are inconsistent about honoring EXIF orientation across platforms.
/// Call this once, right after picking an image, and use only the returned
/// bytes from then on — that removes the ambiguity instead of trying to keep
/// two decoders' conventions in sync.
Uint8List normalizeOrientation({required List<int> imageBytes}) => RustLib
    .instance
    .api
    .crateApiSolverNormalizeOrientation(imageBytes: imageBytes);

/// Load the star-catalog pattern database (bundled as a Flutter asset and
/// passed here as raw bytes) once at app startup.
void loadDatabase({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSolverLoadDatabase(bytes: bytes);

bool isDatabaseLoaded() =>
    RustLib.instance.api.crateApiSolverIsDatabaseLoaded();

/// Solve an image (JPEG/PNG bytes, e.g. from an image picker) against the
/// loaded database, given an estimated horizontal FOV in degrees.
///
/// Not marked `#[frb(sync)]`: flutter_rust_bridge runs this on a worker
/// thread automatically, keeping the UI isolate free during the solve.
Future<SolveOutcome> solveImage({
  required List<int> imageBytes,
  required double fovDeg,
  required double fovErrorDeg,
}) => RustLib.instance.api.crateApiSolverSolveImage(
  imageBytes: imageBytes,
  fovDeg: fovDeg,
  fovErrorDeg: fovErrorDeg,
);

class SolveOutcome {
  final bool success;
  final double raDeg;
  final double decDeg;
  final double fovDeg;
  final double rollDeg;
  final int matchedStars;
  final double rmseArcsec;
  final double solveTimeMs;

  /// Pixel coordinates (top-left origin, matching the source image) of the
  /// matched stars, for drawing a highlight overlay. Same length as
  /// `matched_star_y` and `matched_star_catalog_id`; empty on failure.
  final Float32List matchedStarX;
  final Float32List matchedStarY;

  /// Catalog ID for each matched star, same order as `matched_star_x`/`y`.
  /// Negative = Hipparcos gap-fill star, with the HIP number being
  /// `-id` (see `download_gaia_catalog.py`'s merge convention); positive =
  /// a Gaia DR3 `source_id`, which has no common name to look up.
  final Int64List matchedStarCatalogId;
  final String? error;

  const SolveOutcome({
    required this.success,
    required this.raDeg,
    required this.decDeg,
    required this.fovDeg,
    required this.rollDeg,
    required this.matchedStars,
    required this.rmseArcsec,
    required this.solveTimeMs,
    required this.matchedStarX,
    required this.matchedStarY,
    required this.matchedStarCatalogId,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      raDeg.hashCode ^
      decDeg.hashCode ^
      fovDeg.hashCode ^
      rollDeg.hashCode ^
      matchedStars.hashCode ^
      rmseArcsec.hashCode ^
      solveTimeMs.hashCode ^
      matchedStarX.hashCode ^
      matchedStarY.hashCode ^
      matchedStarCatalogId.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolveOutcome &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          raDeg == other.raDeg &&
          decDeg == other.decDeg &&
          fovDeg == other.fovDeg &&
          rollDeg == other.rollDeg &&
          matchedStars == other.matchedStars &&
          rmseArcsec == other.rmseArcsec &&
          solveTimeMs == other.solveTimeMs &&
          matchedStarX == other.matchedStarX &&
          matchedStarY == other.matchedStarY &&
          matchedStarCatalogId == other.matchedStarCatalogId &&
          error == other.error;
}
